SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

ALTER SCHEMA `quizdb`  DEFAULT CHARACTER SET utf8  DEFAULT COLLATE utf8_general_ci ;

CREATE TABLE IF NOT EXISTS `quizdb`.`QUIZ` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `quizdb`.`TOPICS` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `quizdb`.`QUESTIONS` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(255) NOT NULL,
  `DIFFICULTY_RANK` INT(11) NOT NULL,
  `TOPICS_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_QUESTIONS_TOPICS_idx` (`TOPICS_ID` ASC) VISIBLE,
  CONSTRAINT `fk_QUESTIONS_TOPICS`
    FOREIGN KEY (`TOPICS_ID`)
    REFERENCES `quizdb`.`TOPICS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `quizdb`.`QUESTIONS_IN_QUIZZES` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `QUESTIONS_ID` INT(11) NOT NULL,
  `QUIZ_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_QUESTIONS_IN_QUIZZES_QUESTIONS1_idx` (`QUESTIONS_ID` ASC) VISIBLE,
  INDEX `fk_QUESTIONS_IN_QUIZZES_QUIZ1_idx` (`QUIZ_ID` ASC) VISIBLE,
  CONSTRAINT `fk_QUESTIONS_IN_QUIZZES_QUESTIONS1`
    FOREIGN KEY (`QUESTIONS_ID`)
    REFERENCES `quizdb`.`QUESTIONS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_QUESTIONS_IN_QUIZZES_QUIZ1`
    FOREIGN KEY (`QUIZ_ID`)
    REFERENCES `quizdb`.`QUIZ` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `quizdb`.`RESPONSE` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(255) NOT NULL,
  `IS_CORRECT` TINYINT(4) NOT NULL,
  `QUESTIONS_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_RESPONSE_QUESTIONS1_idx` (`QUESTIONS_ID` ASC) VISIBLE,
  CONSTRAINT `fk_RESPONSE_QUESTIONS1`
    FOREIGN KEY (`QUESTIONS_ID`)
    REFERENCES `quizdb`.`QUESTIONS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
